# Generated by Django 3.1.7 on 2021-03-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210328_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover',
            field=models.ImageField(default='https://twirpz.files.wordpress.com/2015/06/twitter-avi-gender-balanced-figure.png?w=640', upload_to='cover_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://novexconsult.com/images/placeholder.png', upload_to='profile_pics'),
        ),
    ]
