# Generated by Django 3.1.7 on 2021-03-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210328_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover',
            field=models.ImageField(default='cover_pics/default_cover.png', upload_to='cover_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/default_profile.png', upload_to='profile_pics'),
        ),
    ]
