# Generated by Django 3.1.7 on 2021-03-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210328_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover',
            field=models.ImageField(default='default_cover.png', upload_to='cover_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_image.png', upload_to='profile_pics'),
        ),
    ]
