# Generated by Django 3.1.7 on 2021-03-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210328_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='profile_pics'),
        ),
    ]
