# Generated by Django 3.1.6 on 2021-03-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210328_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('I', 'Instructor'), ('N', 'Not')], default='N', max_length=1),
        ),
    ]
