# Generated by Django 3.2 on 2021-04-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='achievements',
            field=models.CharField(blank=True, default='Things you have achieved..', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, default='Where are you currently based..', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, default='What is your educational background..', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.CharField(blank=True, default='What is your professional background..', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='topics',
            field=models.CharField(blank=True, default='What are the topics you like to talk about..', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default='Tell ulittle bit more about yourself..', max_length=500),
        ),
    ]
