# Generated by Django 3.2 on 2021-04-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210420_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default='Tell us little bit more about yourself..', max_length=500),
        ),
    ]
