# Generated by Django 3.2 on 2021-04-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default='Update your profile to add more details about yourself', max_length=500),
        ),
    ]
