# Generated by Django 3.2 on 2021-04-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='availability',
            field=models.CharField(choices=[('B', 'Busy'), ('F', 'Free')], default='F', max_length=1),
        ),
    ]
