# Generated by Django 3.2 on 2021-04-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_profile_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='availability',
        ),
        migrations.AddField(
            model_name='profile',
            name='calendar',
            field=models.URLField(blank=True, default='Paste here your Google Calendar shareable link..', max_length=128, unique=True),
        ),
    ]
