# Generated by Django 3.2 on 2021-04-20 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20210420_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='experience',
            new_name='background',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='achievements',
        ),
    ]
