# Generated by Django 3.2 on 2021-04-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20210421_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='calendar',
            field=models.URLField(blank=True, default='Paste here your Google Calendar shareable link..', max_length=128),
        ),
    ]
