# Generated by Django 3.2 on 2021-04-21 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_profile_calendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sessions',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
