# Generated by Django 3.2 on 2021-04-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20210421_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, default='Where am I currently based..', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='background',
            field=models.CharField(blank=True, default='What is my professional background..', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default='More details about me..', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, default='What is my educational background..', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='topics',
            field=models.CharField(blank=True, default='What are the topics I like to talk about..', max_length=500),
        ),
    ]
