# Generated by Django 3.2 on 2021-04-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210326_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, default='Please click the EMBED option under the Share button of your youtube video', max_length=128, unique=True),
        ),
    ]
