# Generated by Django 3.2 on 2021-04-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_post_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, default='Please click the EMBED option under the SHARE button of your Youtube video and paste it here', max_length=128, unique=True),
        ),
    ]
