# Generated by Django 3.2 on 2021-04-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_post_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meeting_link',
            field=models.URLField(blank=True, default='Paste here a prepared Zoom or Gmeet Meeting link that you and the user will use..', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, default='Please click the EMBED option under the SHARE button of your Youtube video and paste it here..', max_length=128, unique=True),
        ),
    ]
