# Generated by Django 3.2 on 2021-04-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210420_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='meeting_link',
            field=models.URLField(blank=True, default='Paste here a prepared Zoom or Gmeet Meeting link that you and your future students will use..', max_length=128, unique=True),
        ),
    ]
