# Generated by Django 3.2 on 2021-04-21 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_post_meeting_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='link',
            new_name='preview_youtube_link',
        ),
    ]
