# Generated by Django 3.2 on 2021-04-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_link_post_preview_youtube_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview_youtube_link',
            field=models.CharField(blank=True, default='Paste the Youtube Video LINK which can be found at the end of the URL', max_length=128, unique=True),
        ),
    ]
